<?php

namespace Database\Seeders;

use App\Models\Plan;
use App\Models\PlanOccupation;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PlanOccupationSeeder extends Seeder
{
    public function run(): void
    {
        $occupationsByPlan = [
            'อาชีพชั้น 1' => [
                ['กรรมการผู้อำนวยการ', 'Chief Executive Officer'],
                ['กรรมการรองผู้จัดการ', 'Executive Vice President'],
                ['ประธานกรรมการ', 'President'],
                ['กรรมการผู้จัดการ', 'Managing Director'],
                ['รองกรรมการผู้จัดการ', 'Deputy Managing Director'],
                ['ผู้ช่วยกรรมการผู้จัดการ', 'Assistant Managing Director'],
                ['ผู้อำนวยการฝ่าย', 'Director'],
                ['รองผู้อำนวยการฝ่าย', 'Deputy Director'],
                ['ผู้ช่วยผู้อำนวยการฝ่าย', 'Assistant Director'],
                ['ผู้จัดการ(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Manager'],
                ['รองผู้จัดการ(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Deputy Manager'],
                ['ผู้ช่วยผู้จัดการ(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Assistant Manager'],
                ['พนักงานบัญชี', 'Accounting Officer'],
                ['พนักงานพิมพ์ดีด', 'Typist'],
                ['เลขานุการ(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Secretary'],
                ['นักธุรกิจ(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Businessman'],
                ['หัวหน้าฝ่าย(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Department Chief'],
                ['ผู้ช่วยหัวหน้าฝ่าย(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Assistant Department Chief'],
                ['หัวหน้าหน่วย(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Unit Chief'],
                ['ผู้พิพากษา', 'Judge'],
                ['ทนายความ(ปฏิบัติงานในสำนักงานเป็นหลัก)', 'Lawyer/Attorney'],
                ['อัยการ', 'Prosecutor'],
                ['ที่ปรึกษากฎหมาย(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Legal Consultant'],
                ['พนักงานฝึกหัดทนายความ(ปฏิบัติงานในสำนักงานเป็นหลัก)', 'Paralegal'],
                ['บรรณาธิการ(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Editor'],
                ['นักประพันธ์(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Author'],
                ['นักวิจารณ์(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Commentator'],
                ['นักแต่งเพลง(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Composer'],
                ['นักดาราศาสตร์ (ไม่มีการปฏิบัติงานนอกสถานที่)', 'Astronomer'],
                ['นักบัญชี', 'Accountant'],
                ['บรรณารักษ์', 'Librarian'],
                ['เศรษฐกร', 'Economist'],
                ['นักจิตวิทยา', 'Psychologist'],
                ['นักสถิติ', 'Statistician'],
                ['อธิบดี', 'Director-General'],
                ['รองอธิบดี', 'Deputy Director-General'],
                ['ผู้ช่วยอธิบดี', 'Assistant Director-General'],
                ['ผู้อำนวยการกอง', 'Division Director'],
                ['ข้าราชการฝ่ายบริหาร(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Executive Government Officer'],
                ['หัวหน้ากอง(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Division Chief'],
                ['รับราชการ/รัฐวิสาหกิจ(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Government Officer/State Enterprise'],
                ['หัวหน้าคณะผู้บริหาร(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Chief Executive'],
                ['หัวหน้าแผนก(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Section Chief'],
                ['ครู-อาจารย์(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Teacher'],
                ['ผู้ช่วยหัวหน้าแผนก(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Assistant Section Chief'],
                ['ผู้จัดการสหกรณ์การเกษตร(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Agricultural Cooperative Manager'],
                ['พนักงานสหกรณ์การเกษตร(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Agricultural Cooperative Officer'],
                ['พนักงานโทรศัพท์/โทรเลข', 'Telephone/Telegraph Operator'],
                ['นักเรียน/นักศึกษา', 'Student'],
                ['สถาปนิก(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Architect'],
                ['มัณฑนากร(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Interior Designer'],
                ['นักออกแบบ(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Designer'],
                ['นักเขียนแบบ(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Draftsman'],
                ['นักอุตุนิยมวิทยา(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Meteorologist'],
                ['นักวิทยาศาสตร์ (ไม่มีการปฏิบัติงานนอกสถานที่หรือมีการทดลอง)', 'Scientist'],
                ['นักชีววิทยา (ไม่มีการปฏิบัติงานนอกสถานที่)', 'Biologist'],
                ['นักการศึกษา (ไม่มีการปฏิบัติงานนอกสถานที่)', 'Educator'],
                ['นักฟิสิกส์ (ปฏิบัติในงานสำนักงาน/งานวิจัยทั่วไป)', 'Physicist'],
                ['นักรัฐศาสตร์', 'Political Scientist'],
                ['นักปรัชญา', 'Philosopher'],
                ['โปรแกรมเมอร์', 'Programmer'],
                ['นักวิเคราะห์ระบบ', 'System Analyst'],
                ['วิศวกรคอมพิวเตอร์', 'Computer Engineer'],
                ['ผู้ให้คำปรึกษาและผู้จัดการท่องเที่ยว(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Travel Consultant and Manager'],
                ['ผู้เชี่ยวชาญด้านอาหาร', 'Nutritionist'],
                ['พระสงฆ์(ปฏิบัติศาสนกิจทั่วไปภายในศาสนสถาน)', 'Monk'],
                ['นักบวช(ปฏิบัติศาสนกิจทั่วไปภายในศาสนสถาน)', 'Priest'],
                ['อาชีพเกี่ยวกับศาสนา(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Religious Occupations'],
                ['เสมียน', 'Clerk'],
                ['แคชเชียร์', 'Cashier'],
                ['พนักงานธุรการ', 'Administrative Officer'],
                ['พนักงานธนาคาร', 'Bank Employee'],
                ['เจ้าหน้าที่ทรัพยากรบุคคล (HR)', 'Human Resources Officer (HR)'],
                ['เจ้าหน้าที่จัดซื้อ(ไม่มีการออกตรวจ/รับสินค้า)', 'Purchasing Officer'],
                ['เจ้าหน้าที่ประสานงาน(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Coordinator'],
                ['เจ้าหน้าที่บริการลูกค้า', 'Customer Service Officer'],
                ['พนักงาน Call Center / Telesales', 'Call Center / Telesales Agent'],
                ['นักวิชาการ(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Academic Officer'],
                ['เจ้าหน้าที่สินเชื่อ(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Credit Officer'],
                ['แม่บ้าน(ปฏิบัติงานภายในอาคารหรือสำนักงาน)', 'Housekeeper (Working indoors or in offices)'],
                ['เจ้าของกิจการหรือผู้บริหารที่ปฏิบัติงานด้านบริหารภายในสำนักงานเป็นหลัก', 'Business owner or executive mainly administrative office work'],
                ['ผู้ที่ปฏิบัติงานภายในสำนักงานหรือสถานประกอบการเป็นหลัก (ไม่มีการใช้เครื่องจักรขนาดใหญ่ และไม่มีการปฏิบัติงานในโรงงาน พื้นที่ก่อสร้าง หรือพื้นที่ที่มีความเสี่ยงอันตราย)', 'Officer or workplace-based workers with no heavy machinery/factories/construction/hazardous areas'],
                ['สามีหรือพ่อบ้านที่อยู่บ้านดูแลงานในบ้าน(ไม่ใช่ลูกจ้างที่รับค่าจ้าง)', 'Househusband'],
                ['ภรรยาหรือแม่บ้านที่อยู่บ้านดูแลงานในบ้าน(ไม่ใช่ลูกจ้างที่รับค่าจ้าง)', 'Housewife'],
                ['ผู้ช่วยเภสัชกร', 'Pharmacy Assistant'],
                ['เจ้าหน้าที่เขียนแบบ', 'Drafting Technician'],
                ['เจ้าหน้าที่ประกันคุณภาพ', 'Quality Assurance Officer'],
                ['เจ้าหน้าที่จัดซื้อ(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Procurement Officer'],
                ['นักวิเคราะห์ข้อมูล', 'Data Analyst'],
                ['นักวิทยาศาสตร์ข้อมูล', 'Data Scientist'],
                ['เจ้าหน้าที่สนับสนุนด้าน IT', 'IT Support Officer'],
                ['นักพัฒนาซอฟต์แวร์', 'Software Developer'],
                ['นักพัฒนาเว็บไซต์', 'Web Developer'],
                ['ผู้ดูแลฐานข้อมูล', 'Database Administrator'],
                ['นักออกแบบกราฟิก', 'Graphic Designer'],
                ['พนักงานต้อนรับ', 'Receptionist'],
                ['เจ้าหน้าที่บริหารสำนักงาน', 'Office Administrator'],
                ['เจ้าหน้าที่ควบคุมเอกสาร', 'Document Controller'],
                ['นักแปล/ล่าม', 'Translator / Interpreter'],
                ['นักวิจัย(ไม่มีการปฏิบัติงานนอกสถานที่)', 'Researcher'],
                ['ศาสตราจารย์', 'Professor'],
                ['ผู้ช่วยบรรณารักษ์', 'Librarian Assistant'],
                ['ที่ปรึกษาทางการเงิน', 'Financial Advisor'],
                ['ที่ปรึกษาการลงทุน', 'Investment Advisor'],
                ['ผู้ตรวจสอบบัญชี', 'Auditor'],
                ['ผู้ตรวจสอบภายใน', 'Internal Auditor'],
                ['ที่ปรึกษาด้านภาษี', 'Tax Consultant'],
                ['นักวิเคราะห์การเงิน', 'Financial Analyst'],
            ],
            'อาชีพชั้น 2' => [
                ['พนักงานขาย/การตลาด', 'Sale/Marketing Officer'],
                ['ผู้ประกาศข่าววิทยุ/โทรทัศน์', 'Newscaster'],
                ['นักดนตรี', 'Musician'],
                ['นักร้อง', 'Singer'],
                ['นักสังคมสงเคราะห์', 'Social worker'],
                ['นักมนุษยวิทยา', 'Anthropologist'],
                ['วิศวกร', 'Engineer'],
                ['ผู้สื่อข่าว', 'Reporter'],
                ['นักแสดง/ดารา', 'Actor/Movie Star'],
                ['นักลีลาศ', 'Social Dancer'],
                ['นักเกษตรศาสตร์/วนศาสตร์', 'Agronomist/Forester'],
                ['นักการส่งข่าว', 'Intelligence Officer'],
                ['ช่างตัดผม', 'Hairdresser'],
                ['คนรับใช้', 'Survent'],
                ['ช่างซัก/รีด', 'Lanndryman'],
                ['บ๋อย/บริกร', 'Waiter'],
                ['วิศวกรไฟฟ้า', 'Electrical Engineer'],
                ['วิศวกรช่างกล', 'Mechanical Engineer'],
                ['วิศวกรอุตสาหกรรม', 'Industrial Engineer'],
                ['วิศวกรเคมี', 'Chemical Engineer'],
                ['ช่างทำขนมอบ', 'Baker'],
                ['ช่างทำนาฬิกา', 'Watchmaker'],
                ['ช่างซ่อมนาฬิกา', 'Watch Repairer'],
                ['เภสัชกร', 'Pharmacist'],
                ['นักเคมี', 'Chemist'],
                ['นักธรณีวิทยา', 'Geologist'],
                ['สัตว์แพทย์', 'Veterinarian'],
                ['ช่างซ่อมเครื่องใช้ไฟฟ้า', 'Electrical Appliance Technician'],
                ['ช่างทำเครื่องดนตรี', 'Music Instrument Technician'],
                ['มัคคุเทศก์', 'Guide'],
                ['พ่อครัว/แม่ครัว', 'Cook'],
                ['เชฟ', 'Chef'],
                ['พนักงานส่งเอกสาร', 'Courier / Document Delivery Worker'],
                ['พ่อค้าแม่ค้าที่ขายของตามแผงลอย ตลาดนัด หรือริมถนน', 'Street vendor'],
                ['เจ้าของหรือผู้ดูแลร้านค้าปลีก', 'Shopkeeper'],
                ['วิทยากร', 'Lecturer / Guest Speaker'],
                ['ตัวแทน/นายหน้าประกันภัย', 'Insurance Agent / Broker'],
                ['พิธีกร', 'Emcee / Host'],
                ['นักข่าว', 'Journalist / Reporter'],
                ['ช่างภาพ', 'Photographer'],
                ['พนักงานบริการในโรงแรมและร้านอาหาร', 'Hotel and restaurant service staff'],
                ['เจ้าหน้าที่สำรวจภัย', 'Surveyor'],
                ['วิศวกรที่ควบคุมงานหรือออกตรวจหน้างานเป็นครั้งคราว', 'Engineer supervising or inspecting sites occasionally'],
                ['ช่างตัดเสื้อ', 'Tailor / Dressmaker'],
                ['ช่างเสริมสวย', 'Beautician'],
                ['ช่างทำหรือซ่อมรองเท้า', 'Shoemaker / Shoe Repairer'],
                ['ช่างซ่อมเครื่องใช้ไฟฟ้าภายในอาคาร', 'Indoor Electrical Appliance Repair Technician'],
                ['ช่างเทคนิคติดตั้งอุปกรณ์ภายในอาคาร', 'Indoor Equipment Installation Technician'],
                ['ช่างติดตั้งระบบสำนักงานหรืออุปกรณ์สื่อสารภายในอาคาร', 'Office System or Indoor Communication Equipment Installation Technician'],
                ['ช่างคอมพิวเตอร์', 'Computer Technician'],
                ['ช่างซ่อมอุปกรณ์อิเล็กทรอนิกส์', 'Electronic Equipment Repair Technician'],
                ['พ่อค้า/แม่ค้าร้านค้าปลีกทั่วไป(ขายสินค้าภายในร้าน ไม่ยก/ขนของหนัก และไม่มีงานเสี่ยงสูง)', 'Retail Shop Owner / Seller'],
                ['นักกายภาพบำบัด', 'Physical Therapist'],
                ['นักกิจกรรมบำบัด', 'Occupational Therapist'],
                ['ผู้ช่วยสัตวแพทย์', 'Veterinary Assistant'],
                ['ผู้ช่วยทันตแพทย์', 'Dental Assistant'],
                ['ช่างเทคนิคสถาปัตยกรรม', 'Architectural Technician'],
                ['เจ้าหน้าที่ควบคุมคุณภาพ', 'Quality Control Officer'],
                ['เจ้าหน้าที่ความปลอดภัยในการทำงาน', 'Safety Officer'],
                ['เจ้าหน้าที่โลจิสติกส์', 'Logistics Officer'],
                ['ตัวแทน/นายหน้าอสังหาริมทรัพย์', 'Real Estate Agent / Broker'],
            ],
            'อาชีพชั้น 3' => [
                ['เร่ขายของด้วยรถ', 'Pedlar'],
                ['เกษตรกร', 'Agriculturist'],
                ['ช่างทาสี', 'Painter'],
                ['ช่างไม้', 'Carpenter'],
                ['จักรยานยนต์รับจ้าง', 'Motorcycle Taxi Driver'],
                ['คนงานก่อสร้าง', 'Construction Worker'],
                ['ช่างยนต์', 'Automotive Mechanic'],
                ['ช่างซ่อมเครื่องจักรกล', 'Industrial Machinery Mechanic'],
                ['พนักงานรักษาความปลอดภัย', 'Security Guard'],
                ['พนักงานขับรถโดยสาร', 'Passenger Transport Driver'],
                ['คนขับรถแท็กซี่ รถขนส่งประจำทาง หรือรถบรรทุก', 'Taxi, Public Transport, or Truck Driver'],
                ['พนักงานเก็บเงินหรือส่งสินค้า', 'Collection or Delivery Worker'],
                ['กรรมกรหรืออาชีพอื่นที่มีความเสี่ยงในระดับเดียวกัน', 'Laborer or Other Occupation with an Equivalent Risk Level'],
                ['ชาวไร่ ชาวนา ชาวสวน', 'Farmer (Crops/Rice/Orchard)'],
                ['ผู้ขับขี่ยานพาหนะเพื่อประกอบอาชีพ เช่น คนขับรถรับจ้าง', 'Professional Driver (Bus/Truck/Taxi)'],
                ['บุรุษไปรษณีย์', 'Postman / Mail Carrier'],
                ['พนักงานรับส่งเอกสาร (ใช้รถจักรยานยนต์)', 'Messenger / Document Delivery (Using motorcycle)'],
                ['พนักงานส่งอาหาร', 'Food Delivery Rider'],
                ['พนักงานขนส่งสินค้า', 'Cargo / Goods Transport Worker'],
                ['พนักงานคลังสินค้า', 'Warehouse Worker'],
                ['พนักงานโหลดสินค้า', 'Cargo Loading Worker'],
                ['คนงานยกของ', 'Porter / Laborer for lifting'],
                ['ช่างก่อสร้าง', 'Construction Worker / Builder'],
                ['คนงานในโรงงานอุตสาหกรรม', 'Factory Worker'],
                ['พนักงานควบคุมเครื่องจักร', 'Machinery Controller / Operator'],
                ['พนักงานสายการผลิตที่ใช้เครื่องจักร', 'Production Line Worker using machinery'],
                ['ช่างซ่อมเครื่องจักร', 'Machine Repair Mechanic'],
                ['ช่างเชื่อมโลหะ', 'Metal Welder'],
                ['ช่างตัดเหล็กหรือช่างตัดไม้ด้วยเครื่องจักร', 'Iron or Wood Cutting Technician using machinery'],
            ],
        ];

        foreach ($occupationsByPlan as $planNameTh => $occupations) {
            $planId = Plan::where('name_th', $planNameTh)->value('id');
            if ($planId === null) {
                throw new \RuntimeException("Plan {$planNameTh} does not exist. Run PlanSeeder first.");
            }

            $slugs = [];
            foreach ($occupations as [$thai, $english]) {
                $baseSlug = Str::slug($english);
                $number = ($slugs[$baseSlug] ?? 0) + 1;
                $slugs[$baseSlug] = $number;
                $slug = $number === 1 ? $baseSlug : "{$baseSlug}-{$number}";

                PlanOccupation::updateOrCreate(
                    ['plan_id' => $planId, 'occupation_slug' => $slug],
                    ['occupation_th' => $thai, 'occupation_en' => $english]
                );
            }
        }
    }
}